### PR TITLE
Fix Contract Error

### LINKED ISSUE #251: Import contract error
**Describe the bug**
When you go to import a contract on the playground, one of two things happen:

1. It says there is a missing contract deployment at the specific address
2. It says there are missing digits and token identifiers, if you refresh the page some of the text is missing

**To Reproduce**
Here's what I do that creates the problem:
1. Go to https://play.onflow.org/ (it loads up the HelloWorld example) and deploy HelloWorld to 0x01
2. Go to the script tab and add import HelloWorld from 0x01
3. Click "Execute"

**Desktop (please complete the following information):**
- It says Cadence V0.20.0 in the top right

**Additional context**
I think there's a larger problem with the playground where if you move too fast it will break very easily

### PR DESCRIPTION
**Pull request by MaxStalker**
Closes: #251

## Testing Procedure:
The following is the process I've used for manual testing:

#### Setup
- Open new Playground
- Click on account **0x01**
- Deploy the contract
- Switch to script
- Update code to
```cdc
import HelloWorld from 0x01
pub fun main(): String {
  return HelloWorld.greeting
}
```
- Execute The Script
#### Expected Result
Script shall be executed with `{"type":"String","value":"Hello, World!"}` result in the log panel.

#### Setup
- Open new Playground
- Save it
- Switch to script editor
- Remove all code
- Add single character to the editor
- Remove that editor and quickly switch editor to either type
- Select original script
#### Expected Result
Editor should be empty.
______

For contributor use:

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/onflow/flow-playground/blob/master/CONTRIBUTING.md))
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [standards mentioned here](https://github.com/onflow/flow-playground/blob/master/CONTRIBUTING.md).
- [ ] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

File: src/hooks/useLanguageServer.ts [hunk 1]
```diff
@@ -87,12 +88,21 @@ export default function useLanguageServer() {
...
+  )
+
   useEffect(() => {
     if (languageServer) {
       languageServer.updateCodeGetter(getCode);
     }
   }, [project.project.accounts]);
 
+  // TODO: Disable this, once the cadence language server package is updated
+  useEffect(debouncedServerRestart, [project.project.accounts, project.active]);
```
Comment (neil-ptr) [inline src/hooks/useLanguageServer.ts:103]: Just for the sake of learning, how does restarting the server on editor change mitigate the bug reported? :)

**Review by neil-ptr — APPROVED** [review]

File: src/hooks/useLanguageServer.ts (hunk 1 above)
Comment (MaxStalker) [reply src/hooks/useLanguageServer.ts:103]: It's not directly connected to #251 ,but current `staging` branch is using newer and a bit broken build of language server. So this PR reverts it back to older version, which requires LS to be restarted when contracts on account is changed :)
