### PR TITLE
Regexp issues, during signers extraction

### LINKED ISSUE #212: Hello World example fails because of Language Server
**Describe the bug**

https://play.onflow.org/f51905e8-6030-4641-9324-11a3f1a6091c

Language Server has problem with signers I guess. Playground doesn't show signers panel on Say Hello Transaction. 

When you remove comments it works.

### PR DESCRIPTION
**Pull request by MaxStalker**
Closes: #212 

Potential improvement for language server as we should read this data from it and not parsing Cadence code on front-end.

### CODE REVIEW

File: src/util/parser.ts [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+export const stripComments = (code: string) => {
+    const commentsRegExp = /(\/\*[\s\S]*?\*\/)|(\/\/.*)/g;
+    return code.replace(commentsRegExp, "");
+};
+
+export const extract = (code: string, keyWord: string) => {
+    const noComments = stripComments(code);
+    const target = collapseSpaces(noComments.replace(/[\n\r]/g, ""));
+
+    console.log({ noComments })
```
Comment (10thfloor) [inline src/util/parser.ts:19]:
```suggestion
```

**Review by 10thfloor — CHANGES_REQUESTED** [review]

File: src/util/parser.ts (hunk 1 above)
Comment (MaxStalker) [reply src/util/parser.ts]: Addressed!

**Review by 10thfloor — APPROVED** [review]
