### PR TITLE
ui fixes and some formatting tweaks

### LINKED ISSUE #539: Design improvements
I marked some design issues on the screenshot attached.

Screenshot 2022-12-20 at 09 21 03

### PR DESCRIPTION
**Pull request by bthaile**
image

Closes: https://github.com/onflow/flow-playground/issues/539

## Description

UI fixes and formatting tweaks

______

For contributor use:

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/onflow/flow-playground/blob/master/CONTRIBUTING.md))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-playground/blob/master/CONTRIBUTING.md).
- [ ] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

File: src/components/Editor/BottomEditorPanel/RenderError.tsx [hunk 1]
```diff
@@ -50,7 +50,7 @@ const RenderError = (props: any) => {
     <Flex sx={styles.root}>
       <Flex sx={styles.list}>
         {list.length > 0
-          ? list.map((item: CadenceProblem, i: number) => {
+          ? list.reverse().map((item: CadenceProblem, i: number) => {
```
Comment (nialexsan) [inline src/components/Editor/BottomEditorPanel/RenderError.tsx]: to avoid array mutation
```suggestion
          ? [...list].reverse().map((item: CadenceProblem, i: number) => {
```
or
```suggestion
          ? list.slice().reverse().map((item: CadenceProblem, i: number) => {
```

**Review by nialexsan — APPROVED** [review]
