### PR TITLE
use new version of language server, style hint messages

### LINKED ISSUE #690: Cannot deploy FlowToken contract on Playground.
**Describe the bug**
Previously, I remember I was able to deploy FlowToken contract on Playground by the following steps. But now a days, it seems becoming impossible. So I am reporting this issue.

**To Reproduce**
1. deploy Testnet's Fungible Token contract to account 0x01 on PlayGround.
FungibleToken contract: https://flow-view-source.com/testnet/account/0x9a0766d93b6608b7/contract/FungibleToken
Screenshots:
スクリーンショット 2023-06-08 18 52 10

2. deploy Testnet's Flow Token contract to account 0x01 on PlayGround.
FlowToken contract: https://flow-view-source.com/testnet/account/0x7e60df042a9c0868/contract/FlowToken
Screenshots:
スクリーンショット 2023-06-08 18 56 46

3. it becomes unrecognized error. "Oops! Something went wrong. If you'd like, please report the Bug. Thank you!"

**Expected behavior**
Can deploy FlowToken contract on Playground.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 113.0.5672.126 

**Additional context**
Thank you in advance.

### LINKED ISSUE #708: "Oops! Something went wrong. If you'd like, please report the Bug. Thank you!"
Screenshot 2023-06-19 at 2 31 55 PM

## During deployment of contract-4 getting this issue, could anyone please help me to solve that!

### PR DESCRIPTION
**Pull request by bthaile**
Closes: #690 
Closes: #708 

## Description

 - Hint from language server to inform user AuthAccount is an anti-pattern.
 - Disable inputs for unsupported arguments.
 - Style tweaks

image

Give user ability to reset a project state.

Screenshot 2023-06-22 at 10 51 27 AM

______

For contributor use:

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/onflow/flow-playground/blob/master/CONTRIBUTING.md))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-playground/blob/master/CONTRIBUTING.md).
- [ ] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

File: src/components/Editor/CadenceEditor/ControlPanel/Arguments/components.tsx [hunk 1]
```diff
@@ -174,7 +172,7 @@ export const Hints: React.FC<HintsProps> = (props: HintsProps) => {
                 onMouseOut={() => hideDecorations()}
               >
                 <ErrorIndex>
-                  <span>{i + 1}</span>
+                  <span>{`${i + 1}) `}</span>
                 </ErrorIndex>
```
Comment (nialexsan) [inline src/components/Editor/CadenceEditor/ControlPanel/Arguments/components.tsx]: add padding/margin instead of using spaces

**Review by nialexsan — APPROVED** [review]
non-blocking suggestion
