### PR TITLE
LanguageServer and Bool Arguments Fixes

### LINKED ISSUE #194: Failing to pass Bool argument
It's impossible to pass value of type `Bool` to scripts and transactions.

Playground which illustrates the problem can be found here:
https://play.onflow.org/539dfe50-fa3e-4c06-b132-cb32a06dcaa7?type=script&id=07af0649-f83e-46a1-9af9-a1ac73bd376b

### PR DESCRIPTION
**Pull request by MaxStalker**
Closes: #194 and #198 

## Description
CadenceEditor is still being render, but hidden with `display: none` CSS.
Fixes the error without big refactoring, which potentially can introduce new bugs and issues.

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/onflow/flow-playground/blob/master/CONTRIBUTING.md))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-playground/blob/master/CONTRIBUTING.md).
- [ ] Updated relevant documentation 
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

File: src/containers/Editor/components.tsx [hunk 1]
```diff
@@ -230,10 +236,9 @@ const EditorContainer: React.FC<EditorContainerProps> = ({
   }
 
   const isReadmeEditor = active.type === 4;
-  const isCodeEditor = !isReadmeEditor;
 
   return (
-    <MainRoot>
+    /*    <MainRoot>
```
Comment (10thfloor) [inline src/containers/Editor/components.tsx:241]: Should remove this commented code?

**Review by 10thfloor — CHANGES_REQUESTED** [review]

File: src/containers/Editor/components.tsx (hunk 1 above)
Comment (MaxStalker) [reply src/containers/Editor/components.tsx]: Absolutely! Pushed the commit with those changes just now.
